spring:
  application:
    name: Hello-service
    version: 1.2
management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    service-name: Hello-Service
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

#otel:
#  exporter:
#    otlp:
#      spanProcessors: com.example.CustomSpanProcessor

